version: '3'

services:
  database:
    image: postgres:13.3
    hostname: database-postgres
    container_name: database-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped